version: "3.9"

services:
  web:
    build: ./backend 
    volumes:
      - ./backend:/code/ 
    ports:
      - "8001:8001"
    restart: on-failure

  haproxy:
    image: haproxy:latest
    volumes:
      - ./data/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro 
      - ./data/pki/issued/:/usr/local/certificates
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - web
    restart: on-failure